# Generated by Django 3.2.9 on 2021-11-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='ano',
            field=models.CharField(default='1999', max_length=10),
        ),
    ]
