# Generated by Django 3.2.9 on 2021-12-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ronda', '0004_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='nota_fiscal',
            field=models.IntegerField(),
        ),
    ]
